services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: ["poetry", "run", "uvicorn", "--reload", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  node_modules:
